<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ledgerline-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Ledger\Ledgerline.Ledger\Ledgerline.Ledger.csproj" />
    <ProjectReference Include="..\Services\Payments\Ledgerline.Payments\Ledgerline.Payments.csproj" />
    <ProjectReference Include="..\Services\Fraud\Ledgerline.Fraud\Ledgerline.Fraud.csproj" />
    <ProjectReference Include="..\Ledgerline.Gateway\Ledgerline.Gateway.csproj" />
  </ItemGroup>

</Project>
