<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Ledger\Ledgerline.Ledger\Ledgerline.Ledger.csproj" />
    <ProjectReference Include="..\..\src\Services\Payments\Ledgerline.Payments\Ledgerline.Payments.csproj" />
    <ProjectReference Include="..\..\src\Services\Fraud\Ledgerline.Fraud\Ledgerline.Fraud.csproj" />
  </ItemGroup>
</Project>
